# Generated by Django 3.1.7 on 2021-03-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tigId', models.IntegerField(default='-1')),
                ('quantity', models.IntegerField(default='0')),
                ('totalPrice', models.IntegerField(default='0')),
                ('isSale', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('tigId', 'quantity', 'totalPrice', 'isSale'),
            },
        ),
    ]
