# Generated by Django 3.1.7 on 2021-03-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGain', '0003_auto_20210322_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gain',
            options={'ordering': ('created', 'tigId', 'quantity', 'totalPrice', 'isSale', 'category')},
        ),
        migrations.AddField(
            model_name='gain',
            name='category',
            field=models.IntegerField(default=-1),
        ),
    ]
