# Generated by Django 3.1.7 on 2021-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myManageSale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='discount',
            field=models.FloatField(default='0.0'),
        ),
    ]
