# Generated by Django 3.1.7 on 2021-03-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ('created', 'tigId', 'quantity', 'totalPrice')},
        ),
        migrations.AlterField(
            model_name='cost',
            name='created',
            field=models.CharField(default='', max_length=10),
        ),
    ]
